// Todo componente tem que ser importado
import Description from "@/components/Descriptions";
import Parents from "@/components/Parents";
import User from "@/components/User";
import Welcome from "@/components/Welcome";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Fundamentos do React</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello World!</h1>
        {/*chamando o componente*/}
        <Welcome /> 
        {/*Importando componente User que possui uma expressão JSX */}
        <User/>
        {/*Componente pai que possui componente filho incorporado */}
        <Parents/>
        {/*Chamando componentes e passando as props para o mesmo */}
        <Description name="Babi" age={20} />
      </main>
    </>
  );
}
